### ISSUE TITLE
Authentication problem on https://starboard.gg

### ISSUE THREAD

**Issue by llagerlof** [gzuidhof/starboard-notebook#116]
Some error happened when I try to log in.

My username is only lowercase letters. My password was saved, and I already logged in in the past.

Today I tried to log in after a long period (after I saw this release: https://github.com/gzuidhof/starboard-notebook/releases/tag/v0.15.6-r1). I don't know if is related or not.

This error happended after I clicked the "Log in" button:

![image](https://user-images.githubusercontent.com/193798/172193035-04e82491-dcce-4013-8471-11916b2161b1.png)

**Comment by gzuidhof** [comment]
Hi @llagerlof,

Are you still seeing this error. I have not pushed any changes to the server in any form (in fact, it's been running merily for >6 months now). I am guessing the server is sending an unexpected response or perhaps you are behind a corporate firewall which is intercepting the request? 

In case this issue is still showing, could you poke around in your browser devtools and look at the response body from the server?

**Comment by llagerlof** [comment]
I tried to login now, and the error didn't happen. Same home computer, same browser (Firefox).

Thank you.
