### ISSUE TITLE
JavaScript errors

### ISSUE THREAD

**Issue by arperyan** [gzuidhof/starboard-notebook#13]
Hi,

I have been trying to get the JavaScript to work but I keep getting an error?
![image](https://user-images.githubusercontent.com/20163734/99186676-dedc2f80-2749-11eb-8279-b3f5507e6050.png)

Version: 0.6.4

iFrame examples works perfectly. Am I missing something?

Thanks.

Ryan Arpe

**Comment by gzuidhof** [comment]
Ah.. it turns out by trying to remove unused stuff from the bundle, I removed something that Babel depends on.. I will revert the default runtime version to be 0.6.2  on Starboard.gg while I fix this.

I should really have more automated tests to catch this kind of stuff.. Thank you so much for letting me know.

**Comment by gzuidhof** [comment]
I pushed 0.6.6 which fixes this issue, thank you again :)

**Comment by arperyan** [comment]
Thanks.
