### ISSUE TITLE
Using let instead of var causes issue 

### ISSUE THREAD

**Issue by arperyan** [gzuidhof/starboard-notebook#14]
Hi,

When I write the following I get an issue: 
![image](https://user-images.githubusercontent.com/20163734/99257947-bcace500-280f-11eb-897d-a7ea2062177b.png)

When I change it to var then it fixes the issue: 
![image](https://user-images.githubusercontent.com/20163734/99258049-e108c180-280f-11eb-8faa-d06bc03ef486.png)

Is there a reason for this?

Many Thanks,

Ryan Arpe

**Comment by arperyan** [comment]
FYI - const is also a problem

**Comment by gzuidhof** [comment]
This is by design, the variables const and let are scoped to the cell. Behind the scenes, Javascript actually get rewritten slightly before getting executed to make top-level await possible - but also to enable this cell scoping. Here's a peek behind the curtain:

<img width="1140" alt="Screenshot 2020-11-16 at 18 14 43" src="https://user-images.githubusercontent.com/1039510/99291575-f4c81e00-2837-11eb-8b1a-a689128be950.png">

Three things are going on here:
* **The code is wrapped in an async function to allow for the use of `await`**. There is no way in the browser to have top level await. There's a [proposal for it](https://github.com/tc39/proposal-top-level-await), and it seems to already be implemented in browsers, but there's quite some backlash against it in general browser usage, and for good reason, but in notebooks it's very useful! We may see it in ES Modules in the future (= ESM cell type).
* **The last statement gets wrapped into a variable and returned.** This is necessary to get the output of this async cell, but also to know whether the returned value is actually synchronous or not. It's kind of weird how it works now. There's quite some intricacies in why it has to be on an object as well, but that's too much information for this reply ^^.
* **`var`, `Class` and functions at the top level get rewritten to be in global scope**. The `void (a = 123)` style-statements you see essentially put it on the global (=window) object.

Note there is also the ESM cell type, it has none of this magic (it doesn't need it), it actually evaluates the code as a module by running `import(<code as data uri>)`, which allows you to have "normal" imports like `import bla from "https://cdn.com/my-library"`. Any exports from that module are also put on the global object.

---

So that was  some background on what is going on. You can fairly trivially create your own cell type that performs a vanilla `eval`, but it won't support top level await.

In my experience it's pretty painful to work with: await makes your code much more readable, and any time you re-evaluate a cell with `const` in it it will complain as you can not re-define a const value. In my browser's console:

<img width="396" alt="Screenshot 2020-11-16 at 18 47 59" src="https://user-images.githubusercontent.com/1039510/99294685-4f637900-283c-11eb-80ce-b219a24f0738.png">

I think the current approach is pretty clean solution, want a variable to be accessible in any cell? Use `var` at the top level (or put it on `window` manually), otherwise use `let` and `const`.

**Comment by arperyan** [comment]
Thanks for the explanation and makes perfect sense.
