### ISSUE TITLE
TypeError: Illegal constructor when opening https://starboard.gg/#visualization on an iPad

### ISSUE THREAD

**Issue by IntranetFactory** [gzuidhof/starboard-notebook#25]
I'm not sure if that's the correct place to report the issue - but when I open https://starboard.gg/#visualization on an iPad the notebook remains empty.  On console I saw the error `TypeError: Illegal constructor`

**Comment by gzuidhof** [comment]
Thank you for letting me know. I aim to support browsers released since mid 2018.

It turns out Safari has chosen not to implement [extending native elements using custom elements](https://caniuse.com/mdn-api_customelementregistry_builtin) :(. I have not confirmed that this is the issue, but it's my best guess.

The good news is that there appears to be a [polyfill](https://github.com/ungap/custom-elements-builtin). I'll see if I can add it into starboard-wrap to get it to work.

**Comment by gzuidhof** [comment]
Alright - that's fixed.

What isn't fixed is the prosemirror editor (the WYSIWYG editor), the `prosemirror-math` package currently does not support Safari as it also lacks support for [regex lookbehind](https://https://caniuse.com/?search=lookbehind).

This should be simple to resolve with a try-catch (where Safari simply would never enter math-entering mode.. which seems reasonable enough until Safari gets their act together).

**Comment by gzuidhof** [comment]
Solved in latest version.
