### ISSUE TITLE
Upgrade default Pyodide release version

### ISSUE THREAD

**Issue by bartbroere** [gzuidhof/starboard-notebook#76]
The Pyodide version has released some newer versions. Could we update the default Pyodide release that is included in Starboard Notebook? This is currently still on 0.17.0 if I'm correct.

I'm willing to help to achieve this, and maybe submit a PR.

Somewhat related to this: what would be the recommended way of changing the `artifactsUrl` / `indexUrl` for Pyodide when hosting a notebook?

**Comment by gzuidhof** [comment]
Hi Bart,

I've been working on upgrading to Pyodide 0.18.1 (although progress has died down a bit), it's a little bit more involved than just bumping the version number. Pyodide now ships its own Javascript bindings instead of the need to vendor them yourself (and modifying them to fit your needs - which was pretty terrible).

There are some issues/challenges outstanding, but it's mostly working. Some thinks need to be rethinked though, especially the "return value" of cells. Currently running a cell has a return value which is displayed, but that can be really confusing with Python as it first gets converted into Javascript. What's more is that these cell return values currently leak if they are a PyProxy, i.e. they will never be cleaned up.

This is the relevant commit: https://github.com/gzuidhof/starboard-notebook/commit/887c4e6a336819ecb1b3111d8dd76329d3135624 

You can set your own artifactsUrl with a global, a bit hacky but it can get the job done: https://github.com/gzuidhof/starboard-notebook/blob/e93a34a29b1f08cffb310d96b474d12b9f726037/packages/starboard-python/src/global.ts#L214

**Comment by gzuidhof** [comment]
Updated in release 0.15.0!
